# Generated by Django 5.1 on 2025-04-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precio_producto', '0004_remove_precioproducto_cultivo_and_more'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precio_producto.precioproducto'),
        ),
    ]
