# Generated by Django 5.1 on 2025-04-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='precio',
        ),
    ]
