# Generated by Django 5.1 on 2025-04-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_remove_venta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
