# Generated by Django 5.1 on 2025-04-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='venta',
            table='ventas_venta',
        ),
    ]
