# Generated by Django 5.1 on 2025-04-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_alter_venta_options_alter_venta_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='venta',
            table=None,
        ),
    ]
