# Generated by Django 5.1 on 2024-12-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cosechas', '0001_initial'),
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosecha',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='cultivos.cultivo'),
        ),
    ]
