"""
Django settings for Agrosoft project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y25f0nlxx-^y1tc$12**4)gsf=uy7wkcvt%ahr(*l)cf=7#m5i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.X', '192.168.1.12']
    


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.Usuarios.usuarios',
    'apps.Usuarios.roles',
    'apps.Cultivo.bancal',
    'apps.Cultivo.tipo_plaga',
    'apps.Cultivo.plagas',
    'apps.Cultivo.especies',
    'apps.Cultivo.tipo_especies',
    'apps.Cultivo.cultivos',
    'apps.Cultivo.fase_lunar',
    'apps.Cultivo.tipo_control',
    'apps.Cultivo.semillero',
    'apps.Cultivo.tareas',
    'apps.Cultivo.afecciones',
    'apps.Cultivo.controles',
    'apps.Cultivo.productos_control',
    'apps.Cultivo.plantaciones',
    'apps.Cultivo.tipo_actividad',
    'apps.Cultivo.actividades',
    'apps.Cultivo.ReportePlaga',
    'apps.Iot.datos_meteorologicos',
    'apps.Iot.sensores',
    'apps.Finanzas.pagos',
    'apps.Finanzas.venta',
    'apps.Finanzas.salario',
    'apps.Inventario.herramientas',
    'apps.Inventario.insumos',
    'apps.Inventario.precio_producto',
    'apps.Inventario.bodega',
    'apps.Inventario.bodega_insumo',
    'apps.Inventario.bodega_herramienta',
    'apps.Inventario.bodega_precio_producto',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'apps.Cultivo.residuos',
    'apps.Cultivo.tipos_residuos',
    'apps.Cultivo.programacion',
    'apps.Cultivo.cosechas',
    'apps.Cultivo.lotes',
    'apps.Autenticacion.autenticacion',
    'channels',
    'corsheaders',
    'django_filters',
    'apps.Iot.evapotranspiracion',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'apps.Autenticacion.autenticacion.middleware.amJWTAuthFromCookieMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_EXPOSE_HEADERS = ['Content-Disposition']

ROOT_URLCONF = 'Agrosoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Agrosoft.wsgi.application'
ASGI_APPLICATION = "Agrosoft.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis://127.0.0.1:6379/0")],
        },
    },
}


# Configuración CORS para desarrollo
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Frontend Vite
    "http://127.0.0.1:5173",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]


CORS_ALLOW_ORIGIN_REGEXES = [
    r"^http://localhost:5173$",   
    r"^http://127.0.0.1:5173$",  
]






# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'testdb',
        'USER': 'postgres',
        'PASSWORD': 'hate',
        'HOST': 'localhost', 
        'PORT': '5432',
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = './static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), 
    'ROTATE_REFRESH_TOKENS': True,  
    'BLACKLIST_AFTER_ROTATION': True,

    # Configuración de cookies para JWT
    'SESSION_COOKIE_SAMESITE': 'None',  # Permite el envío de cookies entre sitios
    'SESSION_COOKIE_SECURE': False,  # Asegúrate de usar HTTPS si usas 'None'
    'CSRF_COOKIE_SAMESITE': 'None',  # También configurar el SameSite para CSRF
    'CSRF_COOKIE_SECURE': False,  # Cambia a True en producción (HTTPS)
    
    # Configuración de JWT
    'ALGORITHM': 'HS256',  
    'SIGNING_KEY': SECRET_KEY, 
    'AUTH_HEADER_TYPES': ('Bearer',),  
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}


AUTH_USER_MODEL = 'usuarios.Usuarios'
AUTHENTICATION_BACKENDS = [
    'apps.Autenticacion.autenticacion.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://localhost:5174",  
    "http://127.0.0.1:5174",
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.Autenticacion.autenticacion.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication', 
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'agrosoftadso2024@gmail.com'
EMAIL_HOST_PASSWORD = 'kbup uwpx qxyb lywp' 
DEFAULT_FROM_EMAIL = 'agrosoftadso2024@gmail.com'

USE_TZ = True
TIME_ZONE = 'America/Bogota'