# Generated by Django 5.1 on 2025-04-10 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pago_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='auxilio_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='horas_extras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='periodo_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pago',
            name='periodo_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
