# Generated by Django 5.1 on 2025-04-19 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actividad_estado_actividad_instrucciones_adicionales_and_more'),
        ('pagos', '0003_pago_auxilio_transporte_pago_horas_extras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='auxilio_transporte',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='horas_extras',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='horas_trabajadas',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pago',
            name='tiempo_trabajado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad'),
            preserve_default=False,
        ),
    ]
