# Generated by Django 5.1 on 2025-04-21 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_remove_actividad_cantidadusada_and_more'),
        ('pagos', '0004_remove_pago_auxilio_transporte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-periodo_fin', 'actividad'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tiempo_trabajado',
        ),
        migrations.AddField(
            model_name='pago',
            name='actividad',
            field=models.ForeignKey(default=1, limit_choices_to={'estado': 'COMPLETADA'}, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='actividades.actividad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('periodo_fin__gte', models.F('periodo_inicio'))), name='periodo_fin_mayor_igual_inicio'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(fields=('actividad', 'periodo_inicio', 'periodo_fin'), name='pago_unico_por_actividad_periodo'),
        ),
    ]
