# Generated by Django 5.1 on 2025-04-21 05:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_remove_actividad_cantidadusada_and_more'),
        ('pagos', '0005_alter_pago_options_remove_pago_salario_and_more'),
        ('salario', '0003_rename_auxilio_transporte_salario_valorjornal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveConstraint(
            model_name='pago',
            name='periodo_fin_mayor_igual_inicio',
        ),
        migrations.RemoveConstraint(
            model_name='pago',
            name='pago_unico_por_actividad_periodo',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='fecha_creacion',
            new_name='fecha_calculo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='periodo_fin',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='periodo_inicio',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='total_a_pagar',
        ),
        migrations.AddField(
            model_name='pago',
            name='actividades',
            field=models.ManyToManyField(related_name='pagos', to='actividades.actividad'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_fin',
            field=models.DateField(default='2025-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_inicio',
            field=models.DateField(default='2026-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='jornales',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='salario',
            field=models.ForeignKey(default=45600, on_delete=django.db.models.deletion.PROTECT, to='salario.salario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=5364, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
