# Generated by Django 5.1 on 2025-04-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_remove_actividad_cantidadusada_and_more'),
        ('pagos', '0006_alter_pago_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='actividades',
            field=models.ManyToManyField(blank=True, related_name='pagos', to='actividades.actividad'),
        ),
    ]
