# Generated by Django 5.1 on 2025-04-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_alter_pago_actividades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
    ]
