# Generated by Django 5.1 on 2025-02-20 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='programacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programacion.programacion'),
            preserve_default=False,
        ),
    ]
