# Generated by Django 5.1 on 2025-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_actividad_programacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='programacion',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
