# Generated by Django 5.1 on 2025-04-18 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actividad_estado_actividad_instrucciones_adicionales_and_more'),
        ('herramientas', '0004_herramienta_fecha_registro'),
        ('insumos', '0010_tipoinsumo_insumo_es_compuesto_insumo_tipo_insumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='cantidadUsada',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='usuario',
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuarios',
            field=models.ManyToManyField(related_name='actividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PrestamoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregada', models.BooleanField(default=True)),
                ('devuelta', models.BooleanField(default=False)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_herramientas', to='actividades.actividad')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas.herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.IntegerField(default=0)),
                ('cantidad_devuelta', models.IntegerField(default=0)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_insumos', to='actividades.actividad')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
            ],
        ),
    ]
