# Generated by Django 5.1 on 2024-12-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
        ('bodega_herramienta', '0002_delete_bodegaherramienta'),
        ('bodega_insumo', '0002_delete_bodegainsumo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bodega',
        ),
    ]
