# Generated by Django 5.1 on 2025-03-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='capacidad',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
