# Generated by Django 5.1 on 2024-12-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_especies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('largoCrecimiento', models.IntegerField()),
                ('img', models.ImageField(upload_to='especies_images/')),
                ('fk_tipo_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_especies.tipoespecie')),
            ],
        ),
    ]
