# Generated by Django 5.1 on 2025-04-03 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salario',
            old_name='salario_base',
            new_name='auxilio_transporte',
        ),
        migrations.RenameField(
            model_name='salario',
            old_name='valor_por_hora',
            new_name='salario_minimo',
        ),
        migrations.AddField(
            model_name='salario',
            name='fecha_de_implementacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salario',
            name='fecha_de_vencimiento',
            field=models.DateField(default='2024-07-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salario',
            name='horas_laborales_mes',
            field=models.IntegerField(default=230),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salario',
            name='valor_hora_ordinaria',
            field=models.DecimalField(decimal_places=2, default=6189, max_digits=10),
            preserve_default=False,
        ),
    ]
