# Generated by Django 5.1 on 2025-04-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salario', '0002_rename_salario_base_salario_auxilio_transporte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salario',
            old_name='auxilio_transporte',
            new_name='valorJornal',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='fecha_de_vencimiento',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='horas_laborales_mes',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='salario_minimo',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='valor_hora_ordinaria',
        ),
    ]
