# Generated by Django 5.1 on 2024-12-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_plaga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(upload_to='plagas_images/')),
                ('fk_tipo_plaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_plaga.tipoplaga')),
            ],
        ),
    ]
