# Generated by Django 5.1 on 2024-12-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('tam_x', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tam_y', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pos_y', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pos_x', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
