# Generated by Django 5.1 on 2024-12-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_insumo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BodegaInsumo',
        ),
    ]
