# Generated by Django 5.1 on 2024-12-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herramientas', '0002_delete_herramienta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
