# Generated by Django 5.1 on 2025-04-04 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
