# Generated by Django 5.1 on 2024-12-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0002_initial'),
        ('tipos_residuos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('id_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residuos', to='cultivos.cultivo')),
                ('id_tipo_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residuos', to='tipos_residuos.tiporesiduo')),
            ],
        ),
    ]
