# Generated by Django 5.1 on 2025-04-04 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancal', '0002_alter_bancal_nombre'),
        ('lotes', '0002_alter_lote_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancal',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lotes.lote'),
            preserve_default=False,
        ),
    ]
