# Generated by Django 5.1 on 2025-03-30 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20250312_1419'),
        ('usuarios', '0002_create_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.roles'),
        ),
    ]
