# Generated by Django 5.1 on 2024-12-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fechaDeteccion', models.DateField()),
                ('estado', models.CharField(choices=[('ST', 'Estable'), ('EC', 'En Control'), ('EL', 'Eliminada')], max_length=2)),
                ('id_plaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plagas.plaga')),
            ],
        ),
    ]
