# Generated by Django 5.1 on 2024-12-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afecciones', '0001_initial'),
        ('plantaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afeccion',
            name='id_plantacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantaciones.plantacion'),
        ),
    ]
