# Generated by Django 5.1 on 2025-04-24 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportePlaga', '0001_initial'),
        ('afecciones', '0003_alter_afeccion_nombre'),
        ('bancal', '0003_alter_bancal_lote'),
        ('cultivos', '0003_alter_cultivo_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afeccion',
            old_name='fechaDeteccion',
            new_name='fecha_deteccion',
        ),
        migrations.RenameField(
            model_name='afeccion',
            old_name='id_plaga',
            new_name='plaga',
        ),
        migrations.RemoveField(
            model_name='afeccion',
            name='id_plantacion',
        ),
        migrations.AddField(
            model_name='afeccion',
            name='Bancal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bancal.bancal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afeccion',
            name='cultivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afeccion',
            name='gravedad',
            field=models.CharField(choices=[('L', 'Leve'), ('M', 'Moderada'), ('G', 'Grave')], default='L', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afeccion',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReportePlaga.reporteplaga'),
        ),
        migrations.AlterField(
            model_name='afeccion',
            name='estado',
            field=models.CharField(choices=[('ST', 'Estable'), ('EC', 'En Control'), ('EL', 'Eliminada'), ('AC', 'Activa')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='afeccion',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
