# Generated by Django 5.1 on 2025-04-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afecciones', '0004_rename_fechadeteccion_afeccion_fecha_deteccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afeccion',
            old_name='Bancal',
            new_name='bancal',
        ),
    ]
