# Generated by Django 5.1 on 2025-04-24 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancal', '0003_alter_bancal_lote'),
        ('plagas', '0002_alter_plaga_img_alter_plaga_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('RE', 'Revisado'), ('AT', 'Atendido')], default='PE', max_length=2)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancal.bancal')),
                ('plaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plagas.plaga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
