# Generated by Django 5.1 on 2025-04-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportePlaga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporteplaga',
            old_name='lote',
            new_name='bancal_id',
        ),
    ]
