# Generated by Django 5.1 on 2025-04-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportePlaga', '0002_rename_lote_reporteplaga_bancal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporteplaga',
            old_name='bancal_id',
            new_name='bancal',
        ),
    ]
