# Generated by Django 5.1 on 2025-03-08 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_bodega_capacidad_bodega_ubicacion'),
        ('bodega_herramienta', '0003_initial'),
        ('herramientas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegaherramienta',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas_herramientas', to='bodega.bodega'),
        ),
        migrations.AlterField(
            model_name='bodegaherramienta',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bodegaherramienta',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_bodegas', to='herramientas.herramienta'),
        ),
    ]
