# Generated by Django 5.1 on 2025-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_herramienta', '0004_alter_bodegaherramienta_bodega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegaherramienta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
