# Generated by Django 5.1 on 2025-04-19 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancal', '0003_alter_bancal_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evapotranspiracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_bancal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bancal.bancal')),
            ],
            options={
                'unique_together': {('fk_bancal', 'fecha')},
            },
        ),
    ]
