# Generated by Django 5.1 on 2025-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20250312_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(choices=[('aprendiz', 'Aprendiz'), ('pasante', 'Pasante'), ('instructor', 'Instructor'), ('administrador', 'Administrador')], max_length=20, unique=True),
        ),
    ]
