# Generated by Django 5.1 on 2025-04-04 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo_empacado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
