# Generated by Django 5.1 on 2025-04-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_insumo_fecha_actualizacion_insumo_fecha_caducidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio_insumo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
