# Generated by Django 5.1 on 2025-04-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0005_insumo_precio_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='unidad_medida',
        ),
    ]
