# Generated by Django 5.1 on 2025-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_remove_insumo_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creada_por_usuario', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidad_medida_unidadmedida',
            },
        ),
        migrations.AlterModelTable(
            name='insumo',
            table='insumos_insumo',
        ),
    ]
