# Generated by Django 5.1 on 2025-04-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0007_unidadmedida_alter_insumo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='insumos.unidadmedida'),
        ),
    ]
