# Generated by Django 5.1 on 2025-04-15 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0008_insumo_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='fecha_actualizacion',
        ),
    ]
