# Generated by Django 5.1 on 2025-04-16 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0009_remove_insumo_fecha_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creada_por_usuario', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Insumo',
                'verbose_name_plural': 'Tipos de Insumos',
                'db_table': 'insumos_tiposinsumo',
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='es_compuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo_insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='insumos.tipoinsumo'),
        ),
        migrations.CreateModel(
            name='InsumoCompuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_compuestos', to='insumos.insumo')),
                ('insumo_compuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Insumo Compuesto',
                'verbose_name_plural': 'Insumos Compuestos',
                'db_table': 'insumos_insumocompuesto',
                'unique_together': {('insumo_compuesto', 'insumo_componente')},
            },
        ),
    ]
