# Generated by Django 5.1 on 2025-03-08 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancal', '0002_alter_bancal_nombre'),
        ('datos_meteorologicos', '0001_initial'),
        ('sensores', '0002_remove_sensores_fk_datos_metereologicos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_metereologicos',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='datos_metereologicos',
            name='fk_lote',
        ),
        migrations.RemoveField(
            model_name='datos_metereologicos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='datos_metereologicos',
            name='tipo_dato',
        ),
        migrations.RemoveField(
            model_name='datos_metereologicos',
            name='valor',
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='fecha_medicion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='fk_bancal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bancal.bancal'),
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='fk_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.sensores'),
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='valor_medicion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
