# Generated by Django 5.1 on 2025-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_meteorologicos', '0002_remove_datos_metereologicos_fecha_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_metereologicos',
            name='valor_medicion',
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
