# Generated by Django 5.1 on 2025-04-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancal', '0003_alter_bancal_lote'),
        ('datos_meteorologicos', '0003_remove_datos_metereologicos_valor_medicion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_metereologicos',
            old_name='humidity',
            new_name='ambient_humidity',
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='luminosity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='rain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='soil_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='soil_ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='wind_direction',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='datos_metereologicos',
            name='wind_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Evapotranspiracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fk_bancal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancal.bancal')),
            ],
            options={
                'unique_together': {('fk_bancal', 'fecha')},
            },
        ),
    ]
