# Generated by Django 5.1 on 2025-04-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_meteorologicos', '0004_rename_humidity_datos_metereologicos_ambient_humidity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_metereologicos',
            old_name='wind_direction',
            new_name='direccion_viento',
        ),
        migrations.RenameField(
            model_name='datos_metereologicos',
            old_name='ambient_humidity',
            new_name='humedad_ambiente',
        ),
        migrations.RenameField(
            model_name='datos_metereologicos',
            old_name='rain',
            new_name='humedad_suelo',
        ),
        migrations.RenameField(
            model_name='datos_metereologicos',
            old_name='soil_humidity',
            new_name='lluvia',
        ),
        migrations.RenameField(
            model_name='datos_metereologicos',
            old_name='luminosity',
            new_name='luminosidad',
        ),
        migrations.RenameField(
            model_name='datos_metereologicos',
            old_name='soil_ph',
            new_name='ph_suelo',
        ),
        migrations.RenameField(
            model_name='datos_metereologicos',
            old_name='temperature',
            new_name='temperatura',
        ),
        migrations.RenameField(
            model_name='datos_metereologicos',
            old_name='wind_speed',
            new_name='velocidad_viento',
        ),
    ]
