# Generated by Django 5.1 on 2025-04-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_meteorologicos', '0005_rename_wind_direction_datos_metereologicos_direccion_viento_and_more'),
        ('sensores', '0004_sensor_remove_sensores_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_metereologicos',
            name='fk_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.sensor'),
        ),
    ]
