# Generated by Django 5.1 on 2025-04-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_meteorologicos', '0006_alter_datos_metereologicos_fk_sensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evapotranspiracion',
        ),
    ]
