# Generated by Django 5.1 on 2024-12-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('hora_prog', models.DateTimeField()),
                ('fecha_prog', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
