# Generated by Django 5.1 on 2024-12-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_de_medida', models.IntegerField()),
                ('fechaSiembra', models.DateField()),
                ('fechaEstimada', models.DateField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='semilleros_images/')),
                ('fk_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especies.especie')),
            ],
        ),
    ]
