# Generated by Django 5.1 on 2024-12-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidad_de_medida', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
                ('fechaSiembra', models.DateField()),
                ('Bancal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancal.bancal')),
            ],
        ),
    ]
