# Generated by Django 5.1 on 2025-02-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
