# Generated by Django 5.1 on 2025-04-10 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cosechas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida_gramos', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField()),
                ('cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='cosechas.cosecha')),
            ],
        ),
    ]
