# Generated by Django 5.1 on 2025-04-10 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosechas', '0002_initial'),
        ('precio_producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precioproducto',
            name='cosecha',
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='cosechas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cosechas.cosecha'),
        ),
    ]
