# Generated by Django 5.1 on 2025-04-10 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0003_alter_cultivo_nombre'),
        ('precio_producto', '0002_remove_precioproducto_cosecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precioproducto',
            name='cosechas',
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo'),
        ),
    ]
