# Generated by Django 5.1 on 2025-04-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosechas', '0002_initial'),
        ('precio_producto', '0003_remove_precioproducto_cosechas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precioproducto',
            name='cultivo',
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='Producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosechas.cosecha'),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='stock_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
