# Generated by Django 5.1 on 2025-04-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precio_producto', '0004_remove_precioproducto_cultivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precioproducto',
            name='stock_disponible',
        ),
    ]
