# Generated by Django 5.1 on 2025-04-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0009_remove_insumo_fecha_actualizacion'),
        ('precio_producto', '0005_remove_precioproducto_stock_disponible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precioproducto',
            options={'verbose_name': 'Precio Producto', 'verbose_name_plural': 'Precios Productos'},
        ),
        migrations.RemoveField(
            model_name='precioproducto',
            name='unidad_medida_gramos',
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insumos.unidadmedida'),
        ),
        migrations.AlterModelTable(
            name='precioproducto',
            table='precios_productos_precio_producto',
        ),
    ]
