# Generated by Django 5.1 on 2025-03-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='fk_datos_metereologicos',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='tipo_sensores',
        ),
        migrations.AddField(
            model_name='sensores',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sensores',
            name='medida_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensores',
            name='medida_minima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensores',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sensores',
            name='tipo_sensor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sensores',
            name='unidad_medida',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='SensorAbs',
        ),
    ]
