# Generated by Django 5.1 on 2025-04-16 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_remove_sensores_fk_datos_metereologicos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('medida_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medida_maxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='medida_maxima',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='medida_minima',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='tipo_sensor',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='unidad_medida',
        ),
        migrations.AlterField(
            model_name='sensores',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='sensores',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensores.tiposensor'),
        ),
    ]
