# Generated by Django 5.1 on 2025-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_tiposensor_remove_sensores_medida_maxima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_sensor', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=10)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='unidad_medida',
            field=models.CharField(max_length=10),
        ),
    ]
