# Generated by Django 5.1 on 2024-12-02 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afecciones', '0001_initial'),
        ('productos_control', '0001_initial'),
        ('tipo_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fechaControl', models.DateField()),
                ('id_afeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afecciones.afeccion')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_control.productocontrol')),
                ('id_tipoControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_control.tipocontrol')),
            ],
        ),
    ]
