# Generated by Django 5.1 on 2025-04-24 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='id_afeccion',
            new_name='afeccion',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='fechaControl',
            new_name='fecha_control',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='id_tipoControl',
            new_name='tipo_control',
        ),
        migrations.AddField(
            model_name='control',
            name='efectividad',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=50),
        ),
        migrations.AddField(
            model_name='control',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='control',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
